// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxYkVD6lOxmPZnyrSkKrOV8AV-IUBj1Q',
    appId: '1:222123852968:web:a46e51028ae46b4e1c6e9d',
    messagingSenderId: '222123852968',
    projectId: 'farmacia-2e7e5',
    authDomain: 'farmacia-2e7e5.firebaseapp.com',
    storageBucket: 'farmacia-2e7e5.appspot.com',
    measurementId: 'G-33N8QEDED5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlU-tZzCmCpDdMHHFv_U-rB5DG1p_uKrE',
    appId: '1:222123852968:android:765bbdd5b72e5d521c6e9d',
    messagingSenderId: '222123852968',
    projectId: 'farmacia-2e7e5',
    storageBucket: 'farmacia-2e7e5.appspot.com',
  );
}
